name: bill sync 

on:
  issues:
    types: [opened]
jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ZIP_PASSWORD: ${{ secrets.ZIP_PASSWORD }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    if: ${{ contains(github.event.issue.body, '.zip')}}
    permissions: 
      read-all
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: bill sync
        run: |
          python -u scripts/bill.py "${{ github.event.issue.body }}"